export const baseUrl = "http://localhost:8000/";
export const register = "api/signup";
export const login = "api/login";
export const refresh = "api/refresh";
export const user = "api/user";
export const post = "api/posts/recommended_posts";
export const createpost = "api/posts/";
export const like="api/likes/";
export const oneuser="api/userprofile/";
export const userpost="api/posts/user_posts";
export const razorpay="api/create-razorpay/";
export const userupgrade="api/userplans/"
export const apiUrl = '/api/get-user-profile';
// admin side urls
export const registeredUsers = "api/registeredUsers";
export const userdetail = "api/userdetail";
export const blockuser = "api/blockuser";
export const deletepost="api/deletepost"
export const planss="api/plans/";
