# Generated by Django 4.2.6 on 2023-11-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_shares_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='hashtag',
            field=models.ManyToManyField(related_name='posts', to='posts.hashtags'),
        ),
    ]
