# Generated by Django 4.2.6 on 2023-12-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_follow'),
        ('posts', '0004_alter_posts_user_requirment_intrests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirment',
            name='profession',
            field=models.ManyToManyField(to='user.professions', verbose_name='profession'),
        ),
    ]
