# Generated by Django 4.2.6 on 2024-01-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_requirementsaves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intrests',
            old_name='professional',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='requirment',
            old_name='creater',
            new_name='user',
        ),
    ]
