# Generated by Django 4.2.6 on 2024-01-04 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_follow'),
        ('posts', '0007_rename_professional_intrests_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirment',
            name='profession',
        ),
        migrations.AddField(
            model_name='requirment',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.professions'),
            preserve_default=False,
        ),
    ]
