# Generated by Django 4.2.6 on 2024-01-08 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_alter_answers_qustion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrests',
            name='requirment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intrested', to='posts.requirment'),
        ),
        migrations.AlterField(
            model_name='ratinganswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raitinganswer', to='posts.answers'),
        ),
        migrations.CreateModel(
            name='AnswerReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.answers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
