# Generated by Django 4.2.6 on 2024-01-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_intrests_requirment_alter_ratinganswer_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerreply',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_to_reply', to='posts.answerreply'),
        ),
    ]
