# Generated by Django 4.2.6 on 2023-11-17 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_professions_professionalsprofile_houseownerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseownerprofile',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='professionalsprofile',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='professionalsprofile',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.professions'),
        ),
    ]
